### ISSUE TITLE
Replicate Major & Minor Contributors 

### ISSUE THREAD

**Issue by SidIcarus** [andymeneely/chromium-history#201]
Chris Bird defines an owner of a file as someone who has commit code to a file. He further structures the developers into major and minor contributors
- major contributors - an owner who has contributed 5% or more of code to a file
- minor contributors - an owner who has contributed less then 5% of code to a file.

This percentage is calculated based on the aggregated churn from the number of non-trivial commits a person has made to a file. 

Example:
A file has had a total of 4 commits from 4 people.
* Person 1 is the creator and had a total of 15 lines
* Person 2's commit had a churn of 2 lines
* Person 3's commit had a churn of 20 lines of code
* Person 4's commit had a churn of 10 lines
Everyone but person 2 is a major contributor as they have higher then 5% contribution to the file.

Here's the running todo list:
- [x] Add `num_major_contributors`, `num_minor_contributors`, & `num_commits` to ReleaseFilepath schema
- [x] Rip out the current concept of contributor
- [ ] Determine non-trivial commits (requires churn to be loaded).
   - [x] Add a flag to the `commit` table.
- [ ] For each ReleaseFilepath, determine the number of committers prior to the release date who had more/less than 5% of `num_commits`
- [ ] Write a verify on the dev data for this

Note: The number 5 is arbitrary, so don't worry about it.

**Comment by SidIcarus** [comment]
cfp = Commit_Filepath.select("commit_hash, filepath").order(filepath: :asc)
f = Filepath.joins(commit_filepaths: :commit)

**Comment by andymeneely** [comment]
Number of commits for a release filepath:

To get them all: 
```ruby
Filepath.joins(commit_filepaths: :commit).group('filepaths.filepath').select('filepaths.filepath, count(commits.commit_hash)')
```
To get one:
```ruby
CommitFilepath.where(filepath: 'ui/events/x/device_data_manager.h')
```

**Comment by andymeneely** [comment]
Here's a query for major/minor. Given a filepath `ui/events/x/device_data_manager.h`, and a threshold of 5% at `0` (probably unrealistic, but this query returns one row).

```ruby
CommitFilepath.joins(:commit).where(filepath: 'ui/events/x/device_data_manager.h').group('commits.author_id').select('commits.author_id,count(*)').having('count(*) > 0')
```
Here's a commented explanation:
```ruby
CommitFilepath
  .joins(:commit)
  .select('commits.author_id,count(*)') # need the aggregate function for group by
  .where(filepath: 'ui/events/x/device_data_manager.h') # only look for the file we are asking for
  .group('commits.author_id') # group by the author id so  we can count how many commits they had
  .having('count(*) > 0') # only include major contributors with 1 or more commits
  .size # just need the number of rows here
```

**Comment by SidIcarus** [comment]
CommitFilepat.joins(:commit).select('commit_filepaths.filepath, commits.author_id').group('commit_filepaths.filepath, commits.author_id').order(filepath: :asc)
