### ISSUE TITLE
Parse, query, and analyze time to ownership metrics

### ISSUE THREAD

**Issue by andymeneely** [andymeneely/chromium-history#214]
Let's put together some basic time-to-ownership metrics for ReleaseFilepath so we have a place to start on the analysis. We can get more fancy as we go, but let's get this stable and integrated. 

Let's shoot for Feb 2nd for this.

**Comment by rikal** [comment]
Some initial basic metrics

- **Time to Ownership (TTO):** 1st ownership date - 1st commit date
- **# Commits before Ownership(CBO):** total number of commits before ownership

For ReleaseFilepath:
- **Avg. TTO:** Total TTOs / Number of owners
- **Avg. CBO:** Total CBOs / Number of owners

**Comment by andymeneely** [comment]
We still need verifies on this, and it needs to be actually loaded into release filepath. The code in those commits is completely untested, and will run very slowly since it relies on active record and not aggregate functions in sql. We've got a long way to go on this one.
