### ISSUE TITLE
Upgrade google_drive gem 

### ISSUE THREAD

**Issue by andymeneely** [andymeneely/chromium-history#216]
Looks like the google_drive gem is going to be incompatible on the next version. Let's upgrade, but carefully. Let's do this after the MSR deadline.

See Gemfile at c6f60df081acf39ccece12a84232d62c1dcb2c90

**Comment by bspates** [comment]
I have a branch for this, but implementing it meant using oauth, which has some tricky aspects, like having to visit a webpage during the build to authorize the app access to your google drive. Working on a better work flow for it.

**Comment by andymeneely** [comment]
Ugh. Oauth. Can we set the sheet to allow anonymous access as long as you have a link? I'm thinking that might make production setups easier on other people's machines, and we wouldn't have to do oauth

**Comment by bspates** [comment]
I think that is an option, but there is still some sort of application auth to google. Less of a hassle though
