### ISSUE TITLE
Collect release owners data for other releases

### ISSUE THREAD

**Issue by andymeneely** [andymeneely/chromium-history#225]
We currently have releases for 5.0, 11.0, 19.0, 27.0, and 35.0. The commit hashes are here: https://github.com/andymeneely/chromium-history/blob/master/lib/scripts/release-filepaths.sh

Collect this data and put it in /tmp or somewhere and I'll put it into production. 

Let's do this ASAP - today (Feb 11) would be best.

**Comment by rikal** [comment]
done.
